version: 1.2
workflows:
 - name: DeNovo_build_bacterial_consensus
   subclass: WDL
   primaryDescriptorPath: /workflows/DeNovo_build_bacterial_consensus.wdl
   #testParameterFiles:
    #- empty.json
 - name: build_bacterial_consensus
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_build_bacterial_consensus.wdl
   #testParameterFiles:
    #- empty.json
